### ISSUE TITLE
Threshold of the follower/following count in profanity.

### ISSUE THREAD

**Issue by PublicStarMoon** [free-spirit-dev/bird-shield-blocking#1]
![Screenshot 2024-04-05 155632](https://github.com/free-spirit-dev/bird-shield-blocking/assets/5841212/2b944a9e-6de9-40f7-a768-8cbda531d9ba)

The following/follower counts of the above profanity accounts are larger than 100 in screenshot.  I would suggest increasing(fine tuning) the threshold of `foc`, `frc` in the rules:

`url*=huaren.news&foc<10
club.6parkbbs.com&(foc<20&frc<50&cd<1y)
foc<2&frc<8&txt=/李这.*人|李反贼|李某|李.*狗|李坏逼|李父亲|李老湿|李.*骗子|李.*老师|老头.*李|李.*教师/&/炒作|洗脑|卧底|乱搞|不良关系|一点.*没有|垃圾|大外宣|勾结共党|张口就来|吸.*血|人血馒头|白痴|智障|炮王|道德底线|狂躁症|小人|拙劣.*演技|污染.*环境|老贼|太假了|汉奸|大外宣|花的很/
foc<10&frc<10&info=/^\s*$/&(txt*=瞎逼逼|txt*=白痴|txt*=遭报应|txt*=剪辑的图也信)
foc<5&frc<10&info=/^(\s|\w|[#|?!\(\)\?\:\',–&])*$/&(txt*=老灯)
frc<10&foc<5&info=/^\s*$/&(txt*=李坏逼)
foc<1&frc<3&info=/^\s*$/&txt=/(我觉得|他.*是|这家伙.*是).*渣男/
frc<80&foc<30&info=/^(\s|\w|[#|?!\(\)\?\:\',–&])*$/&txt=/李(老師|方鴻|方鸿|颖|穎)[^]+$/
frc<80&foc<30&!info=/^(\s|\w|[#|?!\(\)\?\:\',–&.@\u00C0-\u00FF\uAC00-\uD7AF])*$/&txt=/李(老師|方鴻|方鸿|颖|穎)[^]+$/`

**Comment by free-spirit-dev** [comment]
Can we communicate on Twitter? This kind of rare situation usually results in being added to a blacklist! A high threshold can easily lead to false positives!
![image](https://github.com/free-spirit-dev/bird-shield-blocking/assets/138019802/06b2c099-702e-49aa-98da-d9d3d28af406)

**Comment by PublicStarMoon** [comment]
Maintaining a block list is fine.

How to capture these new bots posting a single image which contains profanity text?

**Comment by free-spirit-dev** [comment]
暂时没有这个功能,因为图片内容的识别对运行速度的影响太大!
现在对于无法适用拦截规则的推文的解决方案是共享黑名单库!
每个人共享一些,就可以拼凑出一个相对干净的环境!
😅当然现在比较尴尬的是只有一个参考库,没有志愿者共享仓库出来!

**Comment by PublicStarMoon** [comment]
https://github.com/PublicStarMoon/bird-shield-blocking

**Comment by free-spirit-dev** [comment]
不需要创建分支的,你直接创建一个新的非空仓库!
然后在鸟盾中增加一个github的设置就可以了!
推中是设置过程!
https://twitter.com/i/bookmarks?post_id=1723430343997628761

**Comment by PublicStarMoon** [comment]
> 不需要创建分支的,你直接创建一个新的非空仓库! 然后在鸟盾中增加一个github的设置就可以了! 推中是设置过程! https://twitter.com/i/bookmarks?post_id=1723430343997628761

Thanks guy!

I created a repo for maintaining customized block-list:  https://github.com/PublicStarMoon/twitter-block-list

And I found an interesting thing that most of the recent twitter bot accounts are following the same account:

![image](https://github.com/free-spirit-dev/bird-shield-blocking/assets/5841212/5c6a1dea-bde8-4258-b025-46496dfd1599)

When I clicked into the followers' twitter pages, I found that almost all of them belongs to profanity accounts, but there are still some exceptions. 

Anyway, I extended my blocking list quickly and easily by checking the followers of https://twitter.com/JenDannie34102/followers.

**Comment by free-spirit-dev** [comment]
Thank you for sharing the blacklist database!
 Subsequent versions will update to enable bulk blocking of all interactions, such as followers, fans, likes, etc., from a particular user, either by selecting all or by specific conditions.
