### ISSUE TITLE
Unexpected regex match on complicated regex pattern.

### ISSUE THREAD

**Issue by PublicStarMoon** [free-spirit-dev/bird-shield-blocking#2]
Filter:
`(c.id=/1260553941714186241|1586332050528915457/)&sn=/\d+$/&(txt=/^([^@:]*(@\w+|:\/\/t\.co\/\w+)+[^@:]*)+$/)`

Regex pattern:
`/^([^@:]*(@\w+|:\/\/t\.co\/\w+)+[^@:]*)+$/`

The expected behavior is to filter those replies with `@abc` or `://t.co/abc` and any characters around them out.

I tested it online by different regex engine:
![image](https://github.com/free-spirit-dev/bird-shield-blocking/assets/5841212/8e0551bf-bb41-49fb-95da-5fd3de22004e)

But unexpected mismatch shown as below happened, I'm desired to know what's the regex engine it's using

:
![image](https://github.com/free-spirit-dev/bird-shield-blocking/assets/5841212/828cc1ee-b4b5-49e4-86c1-20d97142580c)

**Comment by PublicStarMoon** [comment]
Update:

It works for regex pattern: `txt=/^[^@:]*(@\w+|:\/\/t\.co\/\w+)[^]*$/`

**Comment by PublicStarMoon** [comment]
It seems to be expected by another alternative pattern:
`/^[^@:]*(@\w+|:\/\/t\.co\/\w+){1}[^]*$/`

**Comment by free-spirit-dev** [comment]
原正则中的最后一段 `[^@:]*` 这一部分就相当于匹配除"@:"外的任意值了,
鸟盾是使用的浏览器内置正则引擎,也就是符合所有javascript的
另外如果是要匹配url的话,使用`url*=abc`就好,或者`url=/abc$/`

**Comment by PublicStarMoon** [comment]
Thanks for your help!

Would you mind helping me with another quick question corresponding to the `full_text` field ?

Looks like the reply's `full_text` field content starts with the string `@xxxx` which I guess it should be the post owner's username, is there any reason why put it at the beginning of `full_text`? 

Sometimes I want to check if there is a mention `@` in the tweet's reply, while if the replier mentions user at the beginning of his reply, I cannot tell whether it's mentioned by the replier or it's the owner of tweet.

![image](https://github.com/free-spirit-dev/bird-shield-blocking/assets/5841212/1f440a58-e6f6-4c50-82f7-a1cbe6b6023e)

**Comment by free-spirit-dev** [comment]
下次更新时,会改进这个问题!
现在的full_text是推文原始的full_text,我在下次更新的时候,改为最终显示的full_text,这样就能处理好了!
由于是完整重写这一部分,更新会稍微晚一点!

**Comment by PublicStarMoon** [comment]
Seems that your twitter account was banned by Elon Musk

**Comment by free-spirit-dev** [comment]
是的,以后在这里联系: https://discord.gg/SfDrRRPRvM
