### ISSUE TITLE
Kindly Requesting Clarification on openai.com Permission

### ISSUE THREAD

**Issue by chuangbo** [free-spirit-dev/bird-shield-blocking#4]
Thank you for developing and offering this Chrome extension for free. I noticed during the installation process that the extension requests permission to access openai.com. I’m curious to understand why this permission is required and how it is utilized by the extension.

<img width="1104" alt="image" src="https://github.com/free-spirit-dev/bird-shield-blocking/assets/179978/8cc76781-f2c8-4f3e-9476-614f37f945f1">

**Comment by free-spirit-dev** [comment]
These permissions are reserved for the planned development of the 'Tweet Assistant' feature and are not currently in use. After installation, you can disable open.ai access permissions. For more questions, please visit https://discord.gg/SfDrRRPRvM for communication.

**Comment by chuangbo** [comment]
Thank you very much for your prompt response and for clarifying the purpose of the permission request for openai.com. I appreciate your transparency regarding the planned 'Tweet Assistant' feature.
